[package]
name = "subunit-rust"
description = "A subunit v2 protocol implementation in Rust"
version = "0.1.2"
authors = ["Matthew Treinish <mtreinish@kortar.org>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mtreinish/subunit-rust"
keywords = ["subunit"]
categories = ["development-tools::testing"]

[badges]
travis-ci = {repository = "mtreinish/subunit-rust"}

[dependencies]
chrono = "0.4"
byteorder = "1"
crc = "^1.0.0"

[dependencies.pnet]
version = "0.21.0"